### ISSUE TITLE
Problem creating a box with Capsules

### ISSUE THREAD

**Issue by MaxWiebicke** [eudoxos/woodem#11]
I want to create a box full of capsules with
.... generator=PsdCapsuleGenerator(psdPts=[(.3e-3,0),(.4e-3,.5),(.6e-3,1)],shaftRadiusRatio=(0.5,1.5)) ....

but gives me the following error message: 
Particle larger than half of the cell size encountered.
and closes...

I sent you the complete script I am using for checking whether I am doing sth wrong.

Thanks!

**Comment by eudoxos** [comment]
Hi Max,

I looked at the scenario and it is in fact an interesting case. The problem is that with `tanPhi=0.`, there is nothing to dissipate axial rotation of capsules (numerical damping works on accelerations, so it does not contrain inertial motion). With spheres, there is no dissipation either, but there is never torque applied on spheres (shear load is always perpendicular to the line connecting the contact point with the centroid). The whole system goes nuts (exploding, but in periodic cell), hence the error. The solution is to set `tanPhi` to not zero but something small (like 0.05). 

The packing will not be as compact, but you can achieve that by loading-unloading cycle, by setting `stresses=[-100e4,-10e4]` for PeriIsoCompressor.

It also seems that unbalanced force does not drop as quickly so setting `maxUnabalnced` in PeriIsoCompressor to something like 0.001 helps.

Finally, `Scene.dtSafety` should be lower than default (0.5 seems to be good) so that the integration scheme is more precise, that helps getting unbalanced force down.

So this would be the whole script for capsules:

    import woo
    from minieigen import *
    from woo.core import *
    from woo.dem import *

    S=woo.master.scene=Scene(fields=[DemField()],dtSafety=.5)
    mat=FrictMat(young=1e7,ktDivKn=.4,tanPhi=.05)
    S.plot.plots={'i':('sig_x','sig_y','sig_z'),'i ':('eps_x','eps_y','eps_z'),' i':('unbF',)}

    S.periodic=True
    dim=5e-3 # dimension of the box (below)
    S.cell.setBox(dim,dim,dim)
    S.engines=DemField.minimalEngines(damping=.4)+[ # numerical damping: https://yade-dem.org/doc/formulation.html#numerical-damping
        BoxInlet(
            box=((0,0,0),S.cell.size),
            #generator=PsdSphereGenerator(psdPts=[(.3e-3,0),(.4e-3,.5),(.6e-3,1)]), # particle size distribution (PsdEllipsoidGenerator/PsdCapsuleGenerator for other shapes)
            generator=PsdCapsuleGenerator(psdPts=[(.3e-3,0),(.4e-3,.5),(.6e-3,1)],shaftRadiusRatio=(0.5,1.5)),
            maxMass=-1,maxNum=-1,massRate=0,maxAttempts=200,materials=[mat],
            nDo=1, # run only once
        )
    ]
    S.saveTmp() # save to memory
    S.one()     # generate particles

    def addPlotData(S):
        S.plot.addData(sig=S.lab.iso.sigma,eps=S.cell.trsf.diagonal(),i=S.step,unbF=woo.utils.unbalancedForce())

    S.engines=S.engines[:-1]+[
        PeriIsoCompressor(stresses=[-50e4,-10e4],label='iso',doneHook='S.stop()',maxUnbalanced=0.01), 
        PyRunner(100,'addPlotData(S)'),
    ]
    S.saveTmp()
    S.run()

**Comment by MaxWiebicke** [comment]
Thank you, Vaclav!
